source 'https://rubygems.org'

gem 'rails', '4.0.0'
gem 'sqlite3'
gem 'pg'
gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'bcrypt-ruby', '~> 3.0.0'
gem 'haml-rails'
gem 'simple_form'
gem 'inherited_resources'
gem 'quiet_assets'
gem 'thin'
gem 'twitter-bootstrap-rails'
gem 'twitter'
gem 'omniauth-twitter'
gem 'whenever', :require => false
gem 'unicorn'
gem 'capistrano'
gem 'airbrake'
gem 'gon'