shared: &shared
  site_name: Followgen

development:
  <<: *shared
  root_url: http://localhost:3000
  twitter_key:
  twitter_secret:

test:
  <<: *shared
  root_url: http://localhost:3000

production:
  <<: *shared
  root_url: http://gollowfen.firehawkcreative.com
  twitter_key:
  twitter_secret: