shared: &shared
  site_name: Followgen

development:
  <<: *shared
  root_url: http://localhost:3000
  twitter_key: h1qEd231Plsc18vwPycjHQ
  twitter_secret: 1XXGvpfObPJXciTwy3jgGl3c1Oum4arAi4jHzfIA1JQ

test:
  <<: *shared
  root_url: http://localhost:3000

production:
  <<: *shared
  root_url: http://gollowfen.firehawkcreative.com
  twitter_key:
  twitter_secret: